# Site settings
title: XHQ's Blog
brief-intro: Machine Learning Engineer
baseurl: ""
url: "https://code-0x00.github.io"

permalink: /:categories/:year:month:day-:title

# Links
twitter_username: yohoho233
facebook_username: yohoho233
github_username:  Code-0x00
email: kmsj0x00@163.com
weibo_username: yohoho233
zhihu_username: yohoho233
linkedIn_username: yohoho233
dribbble_username:

description_footer: 好好学习，锻炼身体！
description_header: 机器解放人类

# Comments
duoshuo_shortname: #xhq
disqus_shortname: yohoho233

# Statistic analysis
baidu_tongji_id: ad3e9d62485f6b8a9ed3740c25a376d1
google_analytics_id: UA-72449510-4 # google 分析追踪id

description: XHQ's Blog
author: XHQ
meta: x

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Url
category_dir: category/
tag_dir: tag/

# Excerpt
excerpt_separator: "\n\n\n\n"

# Paginate
plugins: [jekyll-paginate]
paginate: 6
